# Data Exploration with Pandas
<table><tr><td>
<img src="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=" height=300><a href="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=">source</a></td><td><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA" height=300><a href="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA">source</a></td></tr></table>

In [210]:
# importing the package(s) we want to use
import pandas as pd

### Let's explore the movies data set more! ###
We'll use the `pd.read_csv()` function to read the csv file into a DataFrame.

In [211]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

### Initial data exploration

We can examine the contents of the resultant DataFrame using the `head()` and `tail()` commands:

In [212]:
### Take a look at the top 3 values of the file
print(movies.head(3))

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965

In [213]:
### How about the last 5 values of a the file?
print(movies.tail())

                Title      Gross  Gross (Adjusted)  Year
195            Patton   61749765         373287682  1970
196  Fatal Attraction  156645693         371808159  1987
197        Iron Man 2  312433331         371691971  2010
198          Zootopia  341268248         371109157  2016
199         Liar Liar  181410615         370330510  1997

Use the info() method to get a quick description of the dataframe

In [214]:
### Get a quick summary of the data using the info() method
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             200 non-null    object
 1   Gross             200 non-null    int64
 2   Gross (Adjusted)  200 non-null    int64
 3   Year              200 non-null    int64
dtypes: int64(3), object(1)
memory usage: 6.4+ KB

# Working to filter different elements

Using iloc and loc to extract specific rows and columns

In [215]:
### Get the first 10 elements (movies) of the second column and convert it into a series with a name
series1 = movies['Gross'].iloc[:10]
# series1 = movies[movies.columns[1]].iloc[:10]
# 'Gross' is equivalent to movies.columns[1]
series1

0    200852579
1    460998507
2    159287539
3    435110554
4    659363944
5     65500000
6    260758300
7    111721910
8    232906145
9    184925486
Name: Gross, dtype: int64

In [216]:
### Get the names of the first 10 movies and convert it into a series and give it type string
series2 = movies['Title'].iloc[:10]
series2 = series2.astype('string')
series2

0                    Gone with the Wind
1    Star Wars: Episode IV - A New Hope
2                    The Sound of Music
3            E.T. the Extra-Terrestrial
4                               Titanic
5                  The Ten Commandments
6                                  Jaws
7                        Doctor Zhivago
8                          The Exorcist
9       Snow White and the Seven Dwarfs
Name: Title, dtype: string

In [217]:
### Create a smaller dataframe with last 20 elements and all columns except 'Year'. Give the columns new custom names (your choice).
smaller_df = movies.drop(columns=['Year']).tail(20)
smaller_df.columns = ['title', 'gross', 'gross (adjusted)']
smaller_df

                                        title      gross  gross (adjusted)
180                   Guardians of the Galaxy  333176600         385834112
181                                 Furious 7  353007020         384393006
182                       Mission: Impossible  180981856         383664957
183     The Hunger Games: Mockingjay - Part 1  337135885         381611053
184                                   Minions  336045770         381492054
185    Harry Potter and the Half-Blood Prince  302305431         381195025
186                      Saturday Night Fever   94213184         380466039
187                            On Golden Pond  119285432         380274891
188     Austin Powers: The Spy Who Shagged Me  206040086         380038767
189  Harry Potter and the Prisoner of Azkaban  249975996         378596724
190                            Bruce Almighty  242829261         377331774
191                                Funny Girl   52223306         375170115
192                    Mission: Impossible II  215409889         374469239
193                               Rush Hour 2  226164286         374410208
194                                 Apollo 13  173837933         373466649
195                                    Patton   61749765         373287682
196                          Fatal Attraction  156645693         371808159
197                                Iron Man 2  312433331         371691971
198                                  Zootopia  341268248         371109157
199                                 Liar Liar  181410615         370330510

Subsetting the dataframe based on conditions

In [218]:
### Create a smaller dataframe with movies made in the year 2000s
movies_2000s = movies[movies['Year'] == 2000]
movies_2000s.info()
movies_2000s

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 122 to 192
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             3 non-null      object
 1   Gross             3 non-null      int64
 2   Gross (Adjusted)  3 non-null      int64
 3   Year              3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 120.0+ bytes

                              Title      Gross  Gross (Adjusted)  Year
122  How the Grinch Stole Christmas  260044825         450760716  2000
175                       Cast Away  233632142         392548654  2000
192          Mission: Impossible II  215409889         374469239  2000

In [219]:
### How many movies Gross (use 'Gross (Adjusted)') over 1,500,000,000?
high_gross_films = movies[movies['Gross (Adjusted)'] > 1_500_000_000]
high_gross_films.info()
high_gross_films
# Only two movies with 'Gross (Adjusted)' over 1,500,000,000

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             2 non-null      object
 1   Gross             2 non-null      int64
 2   Gross (Adjusted)  2 non-null      int64
 3   Year              2 non-null      int64
dtypes: int64(3), object(1)
memory usage: 80.0+ bytes

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977

Customizing the dataframe

In [220]:
### Use DataFrame.columns to change the column name to 'Movie','Gross', 'Gross_adj', and 'Year'
movies.columns = ['Movie', 'Gross', 'Gross_adj', 'Year']
print(movies.columns[0] + ' ' + movies.columns[1] + ' ' + movies.columns[2] + ' ' + movies.columns[3])

Movie Gross Gross_adj Year

In [221]:
### Set the 'Movies' column as the index
movies = movies.set_index('Movie')
movies
# movies.reset_index()

                                        Gross   Gross_adj  Year
Movie
Gone with the Wind                  200852579  1895421694  1939
Star Wars: Episode IV - A New Hope  460998507  1668979715  1977
The Sound of Music                  159287539  1335086324  1965
E.T. the Extra-Terrestrial          435110554  1329174791  1982
Titanic                             659363944  1270101626  1997
...                                       ...         ...   ...
Patton                               61749765   373287682  1970
Fatal Attraction                    156645693   371808159  1987
Iron Man 2                          312433331   371691971  2010
Zootopia                            341268248   371109157  2016
Liar Liar                           181410615   370330510  1997

[200 rows x 3 columns]

Getting some statistic about the data

In [222]:
### Get some statistical information about the 'Gross' column
pd.options.display.float_format = "{:,.2f}".format

# movies['Gross'].describe()
# movies.get('Gross').describe()
movies.Gross.describe()

count           200.00
mean    256,492,048.62
std     170,567,531.47
min       9,183,673.00
25%     116,926,360.25
50%     234,196,310.00
75%     363,303,312.50
max     936,662,225.00
Name: Gross, dtype: float64

In [223]:
### What is the average 'Gross (Adjusted)' value for Movies from the 1990s?
movies_1990s = movies[(movies['Year'] >= 1990) & (movies['Year'] < 2000)]
movies_1990s.info()
print(movies_1990s)
print("Average Gross (Adjusted):", movies_1990s.Gross.mean())

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, Titanic to Liar Liar
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Gross      29 non-null     int64
 1   Gross_adj  29 non-null     int64
 2   Year       29 non-null     int64
dtypes: int64(3)
memory usage: 928.0+ bytes
                                               Gross   Gross_adj  Year
Movie
Titanic                                    659363944  1270101626  1997
Jurassic Park                              404214720   860163189  1993
Star Wars: Episode I - The Phantom Menace  474544677   846224377  1999
The Lion King                              422783777   835301768  1994
Forrest Gump                               330455270   736829627  1994
Independence Day                           306169268   649049593  1996
Home Alone                                 285761243   634669454  1990
The Sixth Sense                            293506292   539516167  1999
Twister                                    241721524   512427497  1996
Men in Black                               250690539   511758479  1997
Mrs. Doubtfire                             219195243   493652828  1993
Aladdin                                    217350219   491384351  1992
Ghost                                      217631306   482228924  1990
The Lost World: Jurassic Park              229086679   467656700  1997
Terminator 2: Judgment Day                 205881154   456999262  1991
Toy Story                                  222498679   448849236  1995
Toy Story 2                                245852179   448228005  1999
Saving Private Ryan                        217049603   429179732  1998
Beauty and the Beast                       218967620   425057869  1991
The Fugitive                               183875760   416002701  1993
Dances with Wolves                         184208848   409462441  1990
Armageddon                                 201578182   402726348  1998
Batman Forever                             184069126   396446574  1995
Pretty Woman                               178406268   395192868  1990
Home Alone 2: Lost in New York             173585516   392130752  1992
Mission: Impossible                        180981856   383664957  1996
Austin Powers: The Spy Who Shagged Me      206040086   380038767  1999
Apollo 13                                  173837933   373466649  1995
Liar Liar                                  181410615   370330510  1997
Average Gross (Adjusted): 258990280.20689654

In [224]:
### What is the standard deviation of 'Gross (Adjusted)'?
movies_1990s.Gross_adj.std()

203516635.9638107